### PR TITLE
Removes hard wired URL so that "New Room" works everywhere.

### PR DESCRIPTION
**Pull request by dietmarw**

### CODE REVIEW

**Comment by seripap** [comment]
:+1:

**Comment by dietmarw** [comment]
@seripap In 6ec8d9c5a06665289e2dac366060eb913767c8bb you managed to overwrite the change of this PR again. I guess that was not on purpose.

**Comment by alanfriedman** [comment]
@dietmarw Not sure what happened here but we do want to keep your fix in to keep URLs relative. We'll get it back in.

**Comment by dietmarw** [comment]
I guess it was a simple matter of forgetting a rebase before merge ;-)

**Comment by seripap** [comment]
Yeah my bad- I was reorganizing a bunch of stuff and forgot to look it over. Should be back in 83840fa

**Comment by dietmarw** [comment]
:+1:

**Pull request merged**
